---
- hosts: all
  remote_user: ansible
  tasks:
  - name: install docker-py
    sudo: yes
    apt:
      name: python-docker
  - name: docker picasso nginx
    docker:
      name:  nginx
      image: egustafson/nginx
      ports: "80:80"
  - name: docker picasso zookeeper
    docker:
      name: zookeeper
      image: wurstmeister/zookeeper
      ports: "2181:2181"
  - name: docker picasso kafka
    docker:
      name: kafka
      image: wurstmeister/kafka:0.8.2.0
      ports: "9092:9092"
      links: "zookeeper:zk"
      volumes: "/var/run/docker.sock:/var/run/docker.sock"
      env:
        KAFKA_ADVERTISED_HOST_NAME=10.3.7.196
  - name: docker cadvisor
    docker:
      name: cadvisor
      image: google/cadvisor:latest
      ports: "8000:8080"
      volumes:
        - "/:/rootfs:ro"
        - "/var/run:/var/run:rw"
        - "/sys:/sys:ro"
        - "/var/lib/docker:/var/lib/docker:ro"
